name: Build and deploy Node.js app to Azure Web App - OmnisPortal

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Debug - Show directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Public directory contents:"
          ls -la public/

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # Copy web.config using full path
      - name: Copy web.config
        run: |
          echo "Copying web.config from public to dist..."
          cp ./public/web.config ./dist/
          echo "Verifying copy operation..."
          ls -la ./dist/web.config

      - name: Zip artifact for deployment
        run: |
          cd dist
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'OmnisPortal'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CB1585E672E74C3EB49DEC16B67F6A8D }}
          package: ./app